spring:
  datasource:
    url: jdbc:h2:mem:meter-readings
    driverClassName: org.h2.Driver
    username: sa
    password: SQL

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    include-stacktrace: never
